name: Daily Cholera Alert

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  run-alert:
    runs-on: ubuntu-latest

    env:
      DSCI_AWS_EMAIL_ADDRESS: ${{ secrets.DSCI_AWS_EMAIL_ADDRESS }}
      DSCI_AWS_EMAIL_USERNAME: ${{ secrets.DSCI_AWS_EMAIL_USERNAME }}
      DSCI_AWS_EMAIL_PASSWORD: ${{ secrets.DSCI_AWS_EMAIL_PASSWORD }}
      DSCI_AWS_EMAIL_HOST: ${{ secrets.DSCI_AWS_EMAIL_HOST }}
      DSCI_AWS_EMAIL_PORT: ${{ secrets.DSCI_AWS_EMAIL_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R packages
        run: |
          install_if_missing <- function(pkg) {
            if (!pkg %in% installed.packages()) install.packages(pkg)
          }
          pkgs <- c("box", "readr", "dplyr", "purrr", "lubridate", "ggplot2", "janitor",
                    "stringr", "zoo", "gt", "gghdx", "whisker", "emayili", "countrycode")
          lapply(pkgs, install_if_missing)

      - name: Run alert script
        run: Rscript monitoring.R
